### ISSUE TITLE
Operation/troubleshooting documentation

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-local-static-provisioner#76]
In addition to getting start documentation, we need to some operation docs to guide users to operate in the production cluster.

- [x] Deleting/removing the underlying volume: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner#deletingremoving-the-underlying-volume
  - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner#managing-your-local-volumes
- [x] deployment issue when docker --init flag is enabled (https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/50)
- [x] ways to prepare disks in production
  - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner#managing-your-local-volumes
- [x] How to fix when a PV (reclaimPolicy=Delete) is released but not able to be deleted
- [x] do not delete PV to recycle volume
  - provisioner has no reliable way to know whether volume without a matching PV has been used before, so it will not clean up it
- [x] How to upgrade provisioner configuration (related to https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/12)
- [x] How to migrate volumes to another storage class (depends on https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/75)
